### ISSUE TITLE
Erro ao rodar o código

### ISSUE THREAD

**Issue by barbozafernando** [Pesterenan/MechPeste-Java#4]
E ai Renan, beleza?

Cara, ao rodar o código, eu estava tendo o seguinte erro: `java.lang.IllegalArgumentException: Value cannot be null.`

![err](https://user-images.githubusercontent.com/45888984/124358835-7e2a3600-dbf8-11eb-8e42-324b38ed490d.png)

Consegui resolver ele e agora está rodando normal. Porém, acha que precisa abrir um pull request pra subir a versão corrigida pro teu repositório?

Valeu!

**Comment by Pesterenan** [comment]
Fala Fernando!
Decidi remover a implementação da classe Drawing na classe AutoRover porque a versão disponível do KRPC (0.48) não dá suporte a essa nova versão da Unity usada no KSP por enquanto!
